version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/backend_static/static/
      - media:/media/
  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend_static/
  nginx:
    image: nginx:1.19.3
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - ./docs:/usr/share/nginx/html/api/docs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/
      - backend_static:/var/html/static/
      - media:/var/html/media/
    ports:
      - 80:80
