# Generated by Django 3.2.3 on 2023-11-25 21:50

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ('user', 'recipe'),
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное. Укажите название ингредиента.', max_length=100, verbose_name='Название')),
                ('measurement_unit', models.CharField(help_text='Обязательное. Укажите единицу измерения для ингредиента.', max_length=15, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name', 'measurement_unit'),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное. Укажите название для рецепта.', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(help_text='Обязательное. Добавьте изображение рецепта.', upload_to='recipes/images/', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Обязательное. Опишите рецепт приготовления.', verbose_name='Описание')),
                ('cooking_time', models.SmallIntegerField(help_text='Обязательное. Укажите время приготовления в минутах.', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientsRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиента')),
            ],
            options={
                'ordering': ('recipe', 'ingredient'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Данное название тега уже занято!'}, help_text='Обязательное. Не более 10 символов.', max_length=10, unique=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', error_messages={'unique': 'Данный цветовой код уже используется!'}, help_text='Обязательное. Укажите шестнадцатеричный код цвета.', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black')], unique=True, verbose_name='Цветовой код')),
                ('slug', models.SlugField(error_messages={'unique': 'Данный слаг уже используется!'}, help_text='Обязательное. Укажите слаг для тега. Не более 10 символов.', max_length=10, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'корзина покупок',
                'verbose_name_plural': 'Корзины покупок',
                'ordering': ('user', 'recipe'),
                'default_related_name': 'shopping_cart',
            },
        ),
    ]
